### PR TITLE
Added QuickSort implementation in Java

### PR DESCRIPTION
**Pull request by gunishjain**

### CODE REVIEW

**Comment by parthpandyappp** [comment]
@gunishjain **[Last Things]** Your PR doesn't follows `readme.md` guidelines.
Implement user input instead of hardcoded values. Ask for input from user.
Thanks, Happy Hacking!

**Comment by gunishjain** [comment]
@parthpandyappp Sorry, you can check now. I have added the User Input.

**Comment by parthpandyappp** [comment]
@gunishjain I found some errors in your code. Please review and submit again!
After this your contributions will get merged in our project!
Thanks, Happy Hacking!

**Comment by gunishjain** [comment]
@parthpandyappp what error? The code is working fine on my side.

**Comment by parthpandyappp** [comment]
@gunishjain Actually, on my side it asks me to add `import java.util.Scanner;` .
Anyways I've changed your code.
Thanks, Happy Hacking!

**Pull request merged**
