### PR TITLE
Added Quicksort for Go

### PR DESCRIPTION
**Pull request by antran22**

### CODE REVIEW

**Comment by parthpandyappp** [comment]
@antran22 What is quicksort_test.go file for?

**Comment by antran22** [comment]
> @antran22 What is quicksort_test.go file for?

It's for testing the algorithm

**Comment by parthpandyappp** [comment]
@antran22 **[Last Things]** That's good, but can you just remove it? And just keep the algorithmic program here.
Thanks, Happy Hacking!

**Comment by antran22** [comment]
Yes, deleted it

**Comment by parthpandyappp** [comment]
Great work so far!
Thanks, Happy Hacking!

**Pull request merged**
