### PR TITLE
Added Searching Algorithms in Python

### PR DESCRIPTION
**Pull request by gauravagrwal**
Issue #2

### CODE REVIEW

**Comment by parthpandyappp** [comment]
@thegauravagrawal Great work! Can you please change the program file's name in accordance with `readme.md` guidelines?
After that your PR is great to go for merge!
Happy Hacking!

**Comment by gauravagrwal** [comment]
Hey @parthpandyappp, it's now ok you can check.

**Comment by parthpandyappp** [comment]
@thegauravagrawal Good work so far, last thing to be done. Instead of a hard coded values between [0-9] can you please change the code so that it accepts input from the user? So, the searching algo will work on user inputs. 

Thanks,
Happy Hacking!

**Comment by gauravagrwal** [comment]
@parthpandyappp code updated.

**Comment by parthpandyappp** [comment]
Great! @thegauravagrawal Your contributions merged!
Thanks, Happy Hacking!

**Pull request merged**
