### PR TITLE
Issue 11

### PR DESCRIPTION
**Pull request by ajaykhanna123**

### CODE REVIEW

**Comment by parthpandyappp** [comment]
Rename your Folder name as of instructed in `readme.md`.
After that, I'll review your code and merge if it looks good.
Thanks, Happy Hacking!

**Comment by parthpandyappp** [comment]
@ajaykhanna123  Good work so far, last thing to be done. Instead of a hard coded values such as `arr = [12, 11, 13, 5, 6] ` can you please change the code so that it accepts input from the user? So, the searching algo will work on user inputs.

Thanks,
Happy Hacking!

**Comment by ajaykhanna123** [comment]
let me know if any other change required on python  code

**Comment by parthpandyappp** [comment]
@ajaykhanna123 Thanks for your contributions!
I'll review your contribution and let you know the merge status soon!
Thanks, Happy Hacking!

**Comment by parthpandyappp** [comment]
@ajaykhanna123 Changes reviewed! Thanks for contributions!
Happy Hacking!

**Pull request merged**
